# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name : sample_azure_CICD_pipelines

trigger :
  - master 

variables :
  -buildConfigurations: 'release'

pool :
 -vmImage : 'Ubantu-Latest'

steps :
  - task : DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
    displayName: 'Restore'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore'
    displayName: 'build-job'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test.csproj'
      arguments: '--no-restore'
    displayName: 'Test'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      arguments: '--configurations$(buildConfigurations)-no-restore'
      zipAfterPublish: true
    displayName: 'Publish'
  
  


